[package]
name = "exprs"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
license-file = "/license"
keywords = ["parser", "expression parser", "math"]
authors = ["chloe"]

[dependencies]

[lib]
name = "exprs"
path = "src/lib.rs"